In [1]:
import random
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
docs = "you will never know until you try"

In [3]:
input_list = np.asarray(docs.split()).reshape(-1,1)
input_list

array([['you'],
       ['will'],
       ['never'],
       ['know'],
       ['until'],
       ['you'],
       ['try']], dtype='<U5')

In [4]:
# onehot encoding
onehot = OneHotEncoder()
onehot.fit(input_list)
print(onehot.categories_)
onehot_vec = onehot.transform(input_list).toarray()
onehot_vec

[array(['know', 'never', 'try', 'until', 'will', 'you'], dtype='<U5')]


array([[0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0.]])

In [5]:
input_df = pd.DataFrame(onehot_vec, index=docs.split())
input_df

0    1    2    3    4    5
you    0.0  0.0  0.0  0.0  0.0  1.0
will   0.0  0.0  0.0  0.0  1.0  0.0
never  0.0  1.0  0.0  0.0  0.0  0.0
know   1.0  0.0  0.0  0.0  0.0  0.0
until  0.0  0.0  0.0  1.0  0.0  0.0
you    0.0  0.0  0.0  0.0  0.0  1.0
try    0.0  0.0  1.0  0.0  0.0  0.0

In [6]:
X_vec = []
X_vec.append(onehot_vec[1])
for i in range(len(onehot_vec)-2):
    X_vec.append(onehot_vec[i])
    X_vec.append(onehot_vec[i+2])
X_vec.append(onehot_vec[-2])
X_vec

[array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 1., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1.])]

In [7]:
X_vec_df = pd.DataFrame(X_vec)
X_vec_df

0    1    2    3    4    5
0   0.0  0.0  0.0  0.0  1.0  0.0
1   0.0  0.0  0.0  0.0  0.0  1.0
2   0.0  1.0  0.0  0.0  0.0  0.0
3   0.0  0.0  0.0  0.0  1.0  0.0
4   1.0  0.0  0.0  0.0  0.0  0.0
5   0.0  1.0  0.0  0.0  0.0  0.0
6   0.0  0.0  0.0  1.0  0.0  0.0
7   1.0  0.0  0.0  0.0  0.0  0.0
8   0.0  0.0  0.0  0.0  0.0  1.0
9   0.0  0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  1.0  0.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  1.0

In [8]:
X = np.matrix(X_vec_df).T
X

matrix([[0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.]])

In [9]:
Y_vec = []
Y_vec.append(onehot_vec[0])
for i in range(1,len(onehot_vec)-1):
    Y_vec.append(onehot_vec[i])
    Y_vec.append(onehot_vec[i])
Y_vec.append(onehot_vec[-1])
Y_vec

[array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 1., 0., 0., 0.])]

In [10]:
Y_vec_df = pd.DataFrame(Y_vec)
Y_vec_df

0    1    2    3    4    5
0   0.0  0.0  0.0  0.0  0.0  1.0
1   0.0  0.0  0.0  0.0  1.0  0.0
2   0.0  0.0  0.0  0.0  1.0  0.0
3   0.0  1.0  0.0  0.0  0.0  0.0
4   0.0  1.0  0.0  0.0  0.0  0.0
5   1.0  0.0  0.0  0.0  0.0  0.0
6   1.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  1.0  0.0  0.0
8   0.0  0.0  0.0  1.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  1.0
10  0.0  0.0  0.0  0.0  0.0  1.0
11  0.0  0.0  1.0  0.0  0.0  0.0

In [11]:
Y = np.matrix(Y_vec_df).T
Y

matrix([[0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.]])

In [12]:
i_node = len(set(docs.split()))
h_node = 4

In [13]:
w1 = np.random.random(size=(i_node,h_node))
w2 = np.random.random(size=(h_node,i_node))
print(w1)
print(w2)

[[0.5365147  0.88067092 0.66082953 0.01774051]
 [0.25287792 0.88156401 0.19018949 0.20351112]
 [0.92293257 0.0321786  0.31312098 0.73956728]
 [0.87132069 0.35043621 0.48798632 0.8865782 ]
 [0.26205413 0.68839593 0.04935834 0.54632096]
 [0.82722089 0.51503532 0.3698723  0.53110958]]
[[0.30523047 0.37251139 0.82971397 0.96342064 0.33325026 0.3778721 ]
 [0.37986539 0.30650151 0.64182306 0.18092732 0.54403599 0.60519916]
 [0.00124126 0.67092369 0.35572274 0.28285135 0.71909061 0.50566167]
 [0.53144168 0.03990173 0.06778371 0.82024724 0.03519447 0.3797312 ]]


In [14]:
H = np.dot(w1.T, X)
H

matrix([[0.26205413, 0.82722089, 0.25287792, 0.26205413, 0.5365147 ,
         0.25287792, 0.87132069, 0.5365147 , 0.82722089, 0.87132069,
         0.92293257, 0.82722089],
        [0.68839593, 0.51503532, 0.88156401, 0.68839593, 0.88067092,
         0.88156401, 0.35043621, 0.88067092, 0.51503532, 0.35043621,
         0.0321786 , 0.51503532],
        [0.04935834, 0.3698723 , 0.19018949, 0.04935834, 0.66082953,
         0.19018949, 0.48798632, 0.66082953, 0.3698723 , 0.48798632,
         0.31312098, 0.3698723 ],
        [0.54632096, 0.53110958, 0.20351112, 0.54632096, 0.01774051,
         0.20351112, 0.8865782 , 0.01774051, 0.53110958, 0.8865782 ,
         0.73956728, 0.53110958]])

In [15]:
def softmax(wth) :
    return np.exp(wth.T) / np.sum(np.exp(np.array(wth.T)), axis=1, keepdims=True)

In [16]:
WtH_cal = np.dot(w2.T, H)
WtH_cal

matrix([[0.63188369, 0.73084999, 0.52045207, 0.63188369, 0.50854535,
         0.52045207, 0.87084254, 0.50854535, 0.73084999, 0.87084254,
         0.68735622, 0.73084999],
        [0.36352737, 0.73535658, 0.50012368, 0.36352737, 0.91385886,
         0.50012368, 0.79476369, 0.91385886, 0.73535658, 0.79476369,
         0.59325598, 0.73535658],
        [0.71384789, 1.18449083, 0.85707391, 0.71384789, 1.24666325,
         0.85707391, 1.18154837, 1.24666325, 1.18449083, 1.18154837,
         0.94793788, 1.18449083],
        [0.83909732, 1.43040569, 0.62385161, 0.83909732, 0.8776949 ,
         0.62385161, 1.76809274, 0.8776949 , 1.43040569, 1.76809274,
         1.59018899, 1.43040569],
        [0.51656237, 0.84053314, 0.70780012, 0.51656237, 1.13373102,
         0.70780012, 0.86312678, 1.13373102, 0.84053314, 0.86312678,
         0.57626487, 0.84053314],
        [0.74805332, 1.01299176, 0.80252836, 0.74805332, 1.07660803,
         0.80252836, 1.12474886, 1.07660803, 1.01299176, 1.12474886,
  

In [17]:
y_hat = softmax(WtH_cal)
y_hat

matrix([[0.16408065, 0.12546186, 0.17809592, 0.20185946, 0.14620895,
         0.18429315],
        [0.12448187, 0.12504412, 0.19593851, 0.25056434, 0.13891236,
         0.16505881],
        [0.14243092, 0.13956476, 0.19943312, 0.15794654, 0.17177838,
         0.18884629],
        [0.16408065, 0.12546186, 0.17809592, 0.20185946, 0.14620895,
         0.18429315],
        [0.10339435, 0.15506801, 0.2163004 , 0.14956033, 0.19320194,
         0.18247496],
        [0.14243092, 0.13956476, 0.19943312, 0.15794654, 0.17177838,
         0.18884629],
        [0.12460524, 0.11547705, 0.17000987, 0.30563783, 0.12364751,
         0.16062251],
        [0.10339435, 0.15506801, 0.2163004 , 0.14956033, 0.19320194,
         0.18247496],
        [0.12448187, 0.12504412, 0.19593851, 0.25056434, 0.13891236,
         0.16505881],
        [0.12460524, 0.11547705, 0.17000987, 0.30563783, 0.12364751,
         0.16062251],
        [0.12992321, 0.118255  , 0.16859936, 0.32046605, 0.11626269,
         0.14649369],

In [18]:
loss = -np.multiply(Y, np.log(y_hat).T).sum() / len(X_vec)
loss

1.8384465159092855

In [19]:
a = 0.01
dif = y_hat.T - Y
w1 = w1 - a * (X * (w2 * dif).T)
w2 = w2 - a * (H * dif.T)