In [1]:
import random
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
docs = "you will never know until you try"

In [3]:
input_list = np.asarray(docs.split()).reshape(-1,1)
input_list

array([['you'],
       ['will'],
       ['never'],
       ['know'],
       ['until'],
       ['you'],
       ['try']], dtype='<U5')

In [ ]:
# onehot encoding
onehot = OneHotEncoder()
onehot.fit(input_list)
print(onehot.categories_)
onehot_vec = onehot.transform(input_list).toarray()
onehot_vec

In [5]:
input_df = pd.DataFrame(onehot_vec, index=docs.split())
input_df

0    1    2    3    4    5
you    0.0  0.0  0.0  0.0  0.0  1.0
will   0.0  0.0  0.0  0.0  1.0  0.0
never  0.0  1.0  0.0  0.0  0.0  0.0
know   1.0  0.0  0.0  0.0  0.0  0.0
until  0.0  0.0  0.0  1.0  0.0  0.0
you    0.0  0.0  0.0  0.0  0.0  1.0
try    0.0  0.0  1.0  0.0  0.0  0.0

In [6]:
X_vec = []
X_vec.append(onehot_vec[1])
for i in range(len(onehot_vec)-2):
    X_vec.append(onehot_vec[i])
    X_vec.append(onehot_vec[i])
X_vec.append(onehot_vec[-2])
X_vec

[array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 1.])]

In [7]:
X_vec_df = pd.DataFrame(X_vec)
X_vec_df

0    1    2    3    4    5
0   0.0  0.0  0.0  0.0  1.0  0.0
1   0.0  0.0  0.0  0.0  0.0  1.0
2   0.0  0.0  0.0  0.0  0.0  1.0
3   0.0  0.0  0.0  0.0  1.0  0.0
4   0.0  0.0  0.0  0.0  1.0  0.0
5   0.0  1.0  0.0  0.0  0.0  0.0
6   0.0  1.0  0.0  0.0  0.0  0.0
7   1.0  0.0  0.0  0.0  0.0  0.0
8   1.0  0.0  0.0  0.0  0.0  0.0
9   0.0  0.0  0.0  1.0  0.0  0.0
10  0.0  0.0  0.0  1.0  0.0  0.0
11  0.0  0.0  0.0  0.0  0.0  1.0

In [8]:
X = np.matrix(X_vec_df).T
X

matrix([[0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.],
        [1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [9]:
Y_vec = []
Y_vec.append(onehot_vec[0])
for i in range(1,len(onehot_vec)-1):
    Y_vec.append(onehot_vec[i])
    Y_vec.append(onehot_vec[i])
Y_vec.append(onehot_vec[-1])
Y_vec

[array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 1., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([0., 1., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([1., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 0., 0., 0., 1.]),
 array([0., 0., 1., 0., 0., 0.])]

In [10]:
Y_vec_df = pd.DataFrame(Y_vec)
Y_vec_df

0    1    2    3    4    5
0   0.0  0.0  0.0  0.0  0.0  1.0
1   0.0  0.0  0.0  0.0  1.0  0.0
2   0.0  0.0  0.0  0.0  1.0  0.0
3   0.0  1.0  0.0  0.0  0.0  0.0
4   0.0  1.0  0.0  0.0  0.0  0.0
5   1.0  0.0  0.0  0.0  0.0  0.0
6   1.0  0.0  0.0  0.0  0.0  0.0
7   0.0  0.0  0.0  1.0  0.0  0.0
8   0.0  0.0  0.0  1.0  0.0  0.0
9   0.0  0.0  0.0  0.0  0.0  1.0
10  0.0  0.0  0.0  0.0  0.0  1.0
11  0.0  0.0  1.0  0.0  0.0  0.0

In [11]:
Y = np.matrix(Y_vec_df).T
Y

matrix([[0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.]])

In [12]:
i_node = len(set(docs.split()))
h_node = 4

In [13]:
w1 = np.random.random(size=(i_node,h_node))
w2 = np.random.random(size=(h_node,i_node))
print(w1)
print(w2)

[[0.2087556  0.0665278  0.33731466 0.6604197 ]
 [0.20010589 0.78626829 0.71535673 0.86157313]
 [0.79622257 0.47321608 0.55608135 0.29645891]
 [0.72463867 0.18213232 0.16584287 0.1452611 ]
 [0.23685927 0.23218826 0.86199159 0.62565595]
 [0.94307595 0.50521359 0.36828012 0.60508007]]
[[0.05351784 0.60069421 0.88730431 0.58653537 0.98712803 0.63748181]
 [0.19594208 0.99906    0.93122611 0.12432708 0.6952962  0.37170138]
 [0.9859812  0.10140211 0.89417599 0.25094174 0.85133446 0.97896199]
 [0.20118209 0.41215778 0.89545801 0.45268788 0.89916459 0.23820004]]


In [14]:
H = np.dot(w1.T, X)
H

matrix([[0.23685927, 0.94307595, 0.94307595, 0.23685927, 0.23685927,
         0.20010589, 0.20010589, 0.2087556 , 0.2087556 , 0.72463867,
         0.72463867, 0.94307595],
        [0.23218826, 0.50521359, 0.50521359, 0.23218826, 0.23218826,
         0.78626829, 0.78626829, 0.0665278 , 0.0665278 , 0.18213232,
         0.18213232, 0.50521359],
        [0.86199159, 0.36828012, 0.36828012, 0.86199159, 0.86199159,
         0.71535673, 0.71535673, 0.33731466, 0.33731466, 0.16584287,
         0.16584287, 0.36828012],
        [0.62565595, 0.60508007, 0.60508007, 0.62565595, 0.62565595,
         0.86157313, 0.86157313, 0.6604197 , 0.6604197 , 0.1452611 ,
         0.1452611 , 0.60508007]])

In [15]:
def softmax(a) :
    y = np.exp(a) / np.sum(np.exp(a))
    return y

In [16]:
WtH_cal = np.dot(w2.T, H)
WtH_cal

matrix([[1.03394992, 0.63431254, 0.63431254, 1.03394992, 1.03394992,
         1.04343365, 1.04343365, 0.48965827, 0.48965827, 0.26721036,
         0.26721036, 0.63431254],
        [0.71952673, 1.35797179, 1.35797179, 0.71952673, 0.71952673,
         1.33337439, 1.33337439, 0.49826508, 0.49826508, 0.69393467,
         0.69393467, 1.35797179],
        [1.75740684, 2.17839448, 2.17839448, 1.75740684, 1.75740684,
         2.32090575, 2.32090575, 1.14017895, 1.14017895, 1.0909493 ,
         1.0909493 , 2.17839448],
        [0.66733016, 0.9822884 , 0.9822884 , 0.66733016, 0.66733016,
         0.78466019, 0.78466019, 0.51432407, 0.51432407, 0.55504503,
         0.55504503, 0.9822884 ],
        [1.69166086, 2.13980593, 2.13980593, 1.69166086, 1.69166086,
         2.12792337, 2.12792337, 1.13331864, 1.13331864, 1.11374843,
         1.11374843, 2.13980593],
        [1.23018645, 1.29364469, 1.29364469, 1.23018645, 1.23018645,
         1.32535467, 1.32535467, 0.6453366 , 0.6453366 , 0.72659787,
  

In [17]:
y_hat = softmax(WtH_cal)
y_hat

matrix([[0.01051465, 0.00705073, 0.00705073, 0.01051465, 0.01051465,
         0.01061484, 0.01061484, 0.00610115, 0.00610115, 0.00488432,
         0.00488432, 0.00705073],
        [0.0076779 , 0.01453836, 0.01453836, 0.0076779 , 0.0076779 ,
         0.01418512, 0.01418512, 0.00615389, 0.00615389, 0.0074839 ,
         0.0074839 , 0.01453836],
        [0.02167644, 0.03302331, 0.03302331, 0.02167644, 0.02167644,
         0.03808136, 0.03808136, 0.01169309, 0.01169309, 0.01113138,
         0.01113138, 0.03302331],
        [0.00728742, 0.00998524, 0.00998524, 0.00728742, 0.00728742,
         0.00819463, 0.00819463, 0.00625351, 0.00625351, 0.00651342,
         0.00651342, 0.00998524],
        [0.02029714, 0.03177326, 0.03177326, 0.02029714, 0.02029714,
         0.03139795, 0.03139795, 0.01161315, 0.01161315, 0.01138808,
         0.01138808, 0.03177326],
        [0.01279437, 0.0136326 , 0.0136326 , 0.01279437, 0.01279437,
         0.01407181, 0.01407181, 0.00712889, 0.00712889, 0.00773238,
  

In [19]:
L = -np.multiply(Y, np.log(y_hat)).sum()/len(X_vec)
L

4.447606347071325

In [20]:
a = 0.01
dif = y_hat - Y
w1 = w1 - a * (X * (w2 * dif).T)
w2 = w2 - a * (H * dif.T)