In [2]:
import numpy as np
import random

In [31]:
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

In [36]:
# 가중치 초기화(행은 입력, 열은 출력)
e = 2
h = 2

w1 = np.random.random(size=(e,h))
b1 = np.random.random(size=(h,1))
w2 = np.random.random(size=(h,1))
b2 = np.random.random(size=(1,1))

# w1 = np.array([[0.5, 0], [0.5, 0]])
# b1 = np.array([[0.6], [0.6]])
# w2 = np.array([[0.7], [0.7]])
# b2 = np.array([[0.8]])

print(w1)
print(b1)
print(w2)
print(b2)

[[0.28174335 0.50690755]
 [0.086064   0.31869082]]
[[0.15197553]
 [0.30704769]]
[[0.34513328]
 [0.95520596]]
[[0.01613605]]


In [37]:
# sum_h1 = (X[0][0] * w1[0][0]) + (X[1][0] * w1[1][0]) + (1 * b1[0][0])
# h1 = 1 / (1 +np.exp(-sum_h1))
# h1

sum_h = np.dot(w1.T, X) + b1
h = 1 / (1 +np.exp(-sum_h))
h

array([[0.53792092, 0.55923047, 0.60676135, 0.627097  ],
       [0.57616447, 0.65152256, 0.6929517 , 0.75632689]])

In [38]:
# sum_h2 = (X[0][0] * w1[0][1]) + (X[1][0] * w1[1][1]) + (1 * b1[1][0])
# h2 = 1 / (1 +np.exp(-sum_h2))
# h2

In [39]:
# sum_h3 = (h1 * w2[0][0]) + (h2 * w2[1][0]) + (1 * b2[0][0])
# h3 = 1 / (1 +np.exp(-sum_h3))
# h3

sum_y_hat = np.dot(w2.T, h) + b2
y_hat = 1 / (1 +np.exp(-sum_y_hat))
y_hat

array([[0.67964617, 0.69666848, 0.70836597, 0.72212283]])

In [40]:
n = 4
L = -1 / n * sum(np.dot(Y, np.log(y_hat).T) + np.dot((1 - Y), np.log(1 - y_hat).T))
L

array([0.78128632])

In [43]:
a = 0.01
dif = y_hat - Y
w2 = w2 - a*np.dot(h, dif.T)
b2 = b2 - a*dif
w1 = w1 - a*np.dot(X, (np.dot(w2, dif) * h * (1-h)).T)
b1 = b1 - a*np.dot(w2, dif) * h * (1-h)