<a href="https://colab.research.google.com/github/2020-nlp-c/nlp-deeplearning/blob/master/quotation_kim/XOR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import random

In [2]:
x = np.array([[0,0,1,1],[0,1,0,1]])
y = np.array([[0,1,1,0]])

In [3]:
h_num = 3
w1 = np.random.rand(2,h_num)
b1 = np.random.rand(h_num,1)
w2 = np.random.rand(h_num,1)
b2 = np.random.rand(1,1)

In [4]:
def sigmoid(X):
	return 1 / (1 + np.exp(-X))

In [5]:
def loss(y, y_hat):
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    return loss

In [6]:
epoch = 100000
learning_rate = 0.01
for epoch in range(epoch):

    # Hidden Node
    h = sigmoid(np.dot(w1.T, x) + b1)

    # y_hat
    y_hat = sigmoid(np.dot(w2.T, h) + b2)

    # Loss 계산
    loss = -1 * 1/x.shape[1] * np.sum(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

    # BackPropagate: Hidden Layer
    dw2 = np.dot(h, (y_hat - y).T)
    db2 = 1 / y.shape[1] * np.sum(y_hat - y, axis = 1, keepdims = True)
    dh  = np.dot(w2, y_hat - y)

    # BackPropagate: Input Layer
    dz1 = dh * h * (1 - h)
    dw1 = np.dot(x, dz1.T)
    db1 = 1 / y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)

    # Weight 수정
    w2 += -learning_rate * dw2
    b2 += -learning_rate * db2
    w1 += -learning_rate * dw1
    b1 += -learning_rate * db1

    if epoch % 10000 == 0:
        predict = y_hat
        print(predict)
        print(loss)

[[0.77444009 0.80115835 0.78206659 0.80596938]]
0.8991052003797843
[[0.49826635 0.49533194 0.50558766 0.50051022]]
0.6921037539641803
[[0.06547725 0.67546309 0.87145817 0.33667201]]
0.25203729432665767
[[0.00507972 0.95814647 0.96137168 0.05730182]]
0.036562644897225764
[[0.00189653 0.97841184 0.97936872 0.03025745]]
0.01882366485140087
[[0.00105251 0.98550289 0.98598719 0.02049438]]
0.012618876185718905
[[6.93295766e-04 9.89098310e-01 9.89400878e-01 1.54833796e-02]]
0.009478819308260902
[[5.02233031e-04 9.91268308e-01 9.91479790e-01 1.24383535e-02]]
0.0075863668097962645
[[3.86435365e-04 9.92719268e-01 9.92877736e-01 1.03932422e-02]]
0.006322313369387184
[[3.09957611e-04 9.93757381e-01 9.93881875e-01 8.92538325e-03]]
0.005418640494304771


### Class화 하기

In [15]:
class XOR:
    def __init__ (self, x, y):
        self.x=x
        self.y=y
        self.w1=[]
        self.b1=[]
        self.w2=[]
        self.b2=[]

    def create_weight(self,h_num):
        self.w1 = np.random.rand(2,h_num)
        self.b1 = np.random.rand(h_num,1)
        self.w2 = np.random.rand(h_num,1)
        self.b2 = np.random.rand(1,1)
    
    def optimize(self,epoch,learning_rate):
        for epoch in range(epoch):
           h = sigmoid(np.dot(self.w1.T, self.x) + self.b1)
           y_hat = sigmoid(np.dot(self.w2.T, h) + self.b2)
           loss = -1 * 1/self.x.shape[1] * np.sum(self.y * np.log(y_hat) + (1 - self.y) * np.log(1 - y_hat))

           if epoch % 10000 == 0:
               predict = np.round(y_hat, 3)
               print('반복횟수: {}, 예측값: {}, Loss: {}'.format(epoch,predict,loss))
           
           dw2 = np.dot(h, (y_hat - self.y).T)
           db2 = 1 / self.y.shape[1] * np.sum(y_hat - self.y, axis = 1, keepdims = True)
           dh  = np.dot(self.w2, y_hat - self.y)
           
           dz1 = dh * h * (1 - h)
           dw1 = np.dot(self.x, dz1.T)
           db1 = 1 / self.y.shape[1] * np.sum(dz1, axis = 1, keepdims = True)
           
           self.w2 += -learning_rate * dw2
           self.b2 += -learning_rate * db2
           self.w1 += -learning_rate * dw1
           self.b1 += -learning_rate * db1

In [16]:
xor=XOR(x,y)

In [17]:
xor.create_weight(3)

In [18]:
xor.optimize(100000,0.01)

반복횟수: 0, 예측값: [[0.823 0.848 0.839 0.857]], Loss: 1.0043252750392249
반복횟수: 10000, 예측값: [[0.261 0.635 0.608 0.492]], Loss: 0.4826810672310794
반복횟수: 20000, 예측값: [[0.007 0.952 0.952 0.068]], Loss: 0.04396250598951713
반복횟수: 30000, 예측값: [[0.002 0.977 0.977 0.033]], Loss: 0.02062558528283398
반복횟수: 40000, 예측값: [[0.001 0.985 0.985 0.022]], Loss: 0.013395213389354631
반복횟수: 50000, 예측값: [[0.001 0.989 0.989 0.016]], Loss: 0.009904415725782548
반복횟수: 60000, 예측값: [[0.001 0.991 0.991 0.013]], Loss: 0.00785288433277875
반복횟수: 70000, 예측값: [[0.    0.993 0.993 0.011]], Loss: 0.006503909115524238
반복횟수: 80000, 예측값: [[0.    0.994 0.994 0.009]], Loss: 0.005549803243054997
반복횟수: 90000, 예측값: [[0.    0.994 0.994 0.008]], Loss: 0.00483950685388967
