In [ ]:
import numpy as np
import random
import math

In [ ]:
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
Y = np.array([[0, 1, 1, 0]])

In [ ]:
H = 3
W_1 = np.random.rand(2, H)
B_1 = np.random.rand(H, 1)
W_2 = np.random.rand(H, 1)
B_2 = np.random.rand(1, 1)

In [ ]:
def sigmoid(x):
	return 1 / (1 + np.exp(-x))

In [ ]:
def loss(Y, Y_hat):
    loss = -1 * 1/X.shape[1] * np.sum(Y * np.log(Y_hat) + (1 - Y) * np.log(1 - Y_hat))
    return loss

In [ ]:
epoch = 100000
learning_rate = 0.01
for epoch in range(epoch):

    # Hidden Node
    H = sigmoid(np.dot(W_1.T, X) + B_1)

    # Y_hat
    Y_hat = sigmoid(np.dot(W_2.T, H) + B_2)

    # Loss 계산
    loss = -1 * 1/X.shape[1] * np.sum(Y * np.log(Y_hat) + (1 - Y) * np.log(1 - Y_hat))

    # BackPropagate: Hidden Layer
    dW_2 = np.dot(H, (Y_hat - Y).T)
    dB_2 = 1 / Y.shape[1] * np.sum(Y_hat - Y, axis = 1, keepdims = True)
    dH  = np.dot(W_2, Y_hat - Y)

    # BackPropagate: Input Layer
    dZ_1 = dH * H * (1 - H)
    dW_1 = np.dot(X, dZ_1.T)
    dB_1 = 1 / Y.shape[1] * np.sum(dZ_1, axis = 1, keepdims = True)

    # Weight 업데이트
    W_2 += -learning_rate * dW_2
    B_2 += -learning_rate * dB_2
    W_1 += -learning_rate * dW_1
    B_1 += -learning_rate * dB_1

    if epoch % 10000 == 0:
        predict = np.round(Y_hat)
        print(predict)
        print(loss)
        print((predict == Y).mean())

predict = np.round(Y_hat)
print(predict)
print(loss)
print((predict == Y).mean())

[[1. 1. 1. 1.]]
0.957421152050443
0.5
[[0. 1. 1. 0.]]
0.3113668312799108
1.0
[[0. 1. 1. 0.]]
0.03940996415187789
1.0
[[0. 1. 1. 0.]]
0.019583556582936666
1.0
[[0. 1. 1. 0.]]
0.012956827996169533
1.0
[[0. 1. 1. 0.]]
0.009666768415728798
1.0
[[0. 1. 1. 0.]]
0.007704857330578048
1.0
[[0. 1. 1. 0.]]
0.00640325642577446
1.0
[[0. 1. 1. 0.]]
0.005477105181618721
1.0
[[0. 1. 1. 0.]]
0.004784633119385206
1.0
[[0. 1. 1. 0.]]
0.004247451158065615
1.0


In [ ]:
len(Y_hat[0])

4

In [ ]:
X.shape[1]

4

In [ ]:
W_1

array([[0.31286129, 0.47611394],
       [0.98256874, 0.47230093]])

In [ ]:
W_2

array([[0.10331809],
       [0.28037995]])

In [ ]:
B_1

array([[1., 1.],
       [1., 1.]])